name: Automated builder of webextension packages

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: upload source code
      uses: actions/upload-artifact@master
      with:
        name: source-code
        path: ./
    - name: npm install and build webext
      run: |
        npm install
        npm run xpi
      env:
        CI: true
    - name: upload built artifacts
      uses: actions/upload-artifact@master
      with:
        name: web-ext-artifact
        path: ./web-ext-artifacts
